[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-Ctarget-feature=+m,+a,+f,+d",
    "-Ctarget-cpu=generic-rv64",
    "-Copt-level=2",
    "-Cdebuginfo=2",
    "-Clink-arg=-nostartfiles",
    "-Clink-arg=-static",
    "-Clinker=riscv64-unknown-elf-gcc",
]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
