name: UserTests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build Docker image
              run: sh ./ci/docker/build.sh

            - name: Show the MR info
              run: |
                  echo "Target branch: '$GITHUB_BASE_REF'"
                  echo "Source branch: '$GITHUB_HEAD_REF'"

            - name: Build
              run: docker run --rm -v ${{ github.workspace }}:/xv6 vityamand/xv6:latest sh -c "cd /xv6 && make && make fs.img && make qemu"

            - name: Test Lab 1
              if: ${{ github.head_ref == 'lab-1' }}
              run: docker run --rm -v ${{ github.workspace }}:/xv6 vityamand/xv6:latest sh -c "cd /xv6 && sh ./ci/test/run.sh dumptests dump2tests usertests"

            - name: Test Lab 2
              if: ${{ github.head_ref == 'lab-2' }}
              run: docker run --rm -v ${{ github.workspace }}:/xv6 vityamand/xv6:latest sh -c "cd /xv6 && sh ./ci/test/run.sh alloctest usertests"

            - name: Test Lab 3
              if: ${{ github.head_ref == 'lab-3' }}
              run: docker run --rm -v ${{ github.workspace }}:/xv6 vityamand/xv6:latest sh -c "cd /xv6 && sh ./ci/test/run.sh cowtest lazytests usertests"

            - name: Test Basic
              if: ${{ ! startsWith(github.head_ref, 'lab-') }}
              run: docker run --rm -v ${{ github.workspace }}:/xv6 vityamand/xv6:latest sh -c "cd /xv6 && sh ./ci/test/run.sh usertests"
